select * from customer_behavior;
ALTER TABLE customer_behavior 
RENAME COLUMN `purchase_amount_usd` TO purchase_amount;

-- what is the totol revenue generated by the male and the female
select gender,  sum(purchase_amount) from customer_behavior group by gender;

-- Which customer used a discount but still spent more than the average purchase amount 
select customer_id, purchase_amount , discount_applied
 from customer_behavior
  where discount_applied = 'yes'
  and purchase_amount >= (select avg(purchase_amount) from customer_behavior);

-- Which are the top 5 product with the highest average review rating
SELECT 
    item_purchased, 
    AVG(review_rating)AS avg_review 
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_review DESC 
LIMIT 5;
-- compare the average purcahse amount betwee standard and express shipping
select avg(purchase_amount), shipping_type
 from customer_behavior where shipping_type in ('Standard', 'Express')
 group by shipping_type;

-- Do subscribed customere spend more? compare average spend and total revenue between subscribere and non-suscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- which 5 products have the highest precentage of purchase with discount applied 
select item_purchased,
round(sum(case when discount_applied ='yes' then 1 else 0 end )*100.0/ count(*),2) as discount_percentage
from customer_behavior
 group by item_purchased 
 order by  discount_percentage
 desc limit 5;
 
 -- segement customers into New Returing and loyal based on their toatl no of precious purchase and show the count of each segementn

With customer_type as (select
customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 1 and 10 then 'Returning'
    Else 'Loyal'
    end as customer_segment
   from customer_behavior
)
select customer_segment, count(*) as 'No of customer'
from customer_type
group by customer_segment;

-- What are the top 3 most purchased product with each catogry
WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchased,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_purchased
FROM ranked_products
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue desc;
  

 
